[project]
name = "deep-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "addict>=2.4.0",
    "backend",
    "einops>=0.8.2",
    "fastapi[standard]>=0.136.1",
    "ml_pipeline",
    "pymupdf>=1.27.2.3",
    "python-multipart>=0.0.27",
    "transformers>=5.7.0",
]

[tool.uv.workspace]
members = [
    "ml",
    "shared",
    "backend",
]

[tool.uv.sources]
backend = { workspace = true }
ml_pipeline = { workspace = true }
shared_utils = { workspace = true }
