#experiment_name: "cat_dog_classifier"
#experiment_name: "transfer_resnet"
experiment_name: "mnist_classifier"
run_name: "run_01"
seed: 42

data:
  dataset_name: "mnist"
  dataset_dir: "ml/data"
  batch_size: 64
  num_workers: 0
  infer_path: "ml/samples/IMG_3290.jpg"  # Path to image for inference

model:
#  name: "CatDogClassifier"
#  name: "TransferResNet"
  name: "mnistclassifier"
  params:
    num_classes: 10
#    freeze: true

training:
  num_epochs: 10
  early_stop_patience: 15
  optimizer:
    name: "Adam"
    learning_rate: 0.001
  scheduler:
    name: "ReduceLROnPlateau"
    factor: 0.1
    scheduler_patience: 7
    min_lr: 0.000001

paths:
    experiments_root: "ml/experiments"
    checkpoints_dirname: "checkpoints"
    logs_dirname: "logs"
    artifacts_dirname: "artifacts"
    config_dirname: "configs"