experiment_name: "cat_dog_classifier"
#experiment_name: "transfer_resnet"
run_name: "run_14"
seed: 42

data:
  dataset_dir: "./data/cats_vs_dogs"
  batch_size: 64
  num_workers: 0

model:
  name: "CatDogClassifier"
#  name: "TransferResNet"
  params:
    num_classes: 2
    freeze: true

training:
  num_epochs: 100
  early_stop_patience: 15
  optimizer:
    name: "Adam"
    learning_rate: 0.001
  scheduler:
    name: "ReduceLROnPlateau"
    factor: 0.1
    scheduler_patience: 7
    min_lr: 0.000001

paths:
    experiments_root: "./experiments"
    checkpoints_dirname: "checkpoints"
    logs_dirname: "logs"
    artifacts_dirname: "artifacts"
    config_dirname: "configs"