model:
#  name: "TransferResNet"
  name: "catdogclassifier"
  params:
    num_classes: 2
    freeze: true

# Data settings
data_dir: "./data/images"
batch_size: 64
num_workers: 0
seed: 42

# Model settings
num_classes: 2
freeze: true

# Training settings
num_epochs: 10
learning_rate: 0.001
save_path: "experiments/run_01/best_model.pth"